service: moonreminder # Name of our service

provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: us-east-1
  memorySize: 128 # 1MB increments, minimum 128, affects pricing
  environment:
    API_KEY: ${ssm:/moonreminder/config/api_key}
    LOCATION: ${ssm:/moonreminder/config/location}
    MY_AWS_ACCESS_KEY_ID: ${ssm:/moonreminder/config/aws_access_key}
    MY_AWS_SECRET_ACCESS_KEY: ${ssm:/moonreminder/config/aws_secret_access_key}
    MY_AWS_REGION: ${ssm:/moonreminder/config/aws_region}
    FROM_ADDRESS:  ${ssm:/moonreminder/config/from_address}
    TO_ADDRESS:  ${ssm:/moonreminder/config/to_address}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

# Endpoint config
functions:
  FetchMoonData:
    handler: bin/aws
    events:
      - schedule:
          rate: cron(0 7 * * ? *)